import os.path
from sys import argv
from pyiga import vform
from pyiga.codegen import cython as backend

def generate(dim):
    code = backend.CodeGen()

    def gen(vf, classname):
        backend.AsmGenerator(vf, classname, code).generate()

    gen(vform.mass_vf(dim), 'MassAssembler')
    gen(vform.stiffness_vf(dim), 'StiffnessAssembler')
    gen(vform.heat_st_vf(dim), 'HeatAssembler_ST')
    gen(vform.wave_st_vf(dim), 'WaveAssembler_ST')
    gen(vform.divdiv_vf(dim), 'DivDivAssembler')

    return code.result()

if __name__ == '__main__':
    if '--generic' in argv[1:]:
        path = os.path.join(os.path.dirname(__file__), "..", "pyiga", "genericasm.pxi")
        with open(path, 'w') as f:
            f.write('# file generated by generate-assemblers.py\n')
            f.write(backend.generate_generic(dim=2))
            f.write(backend.generate_generic(dim=3))

    path = os.path.join(os.path.dirname(__file__), "..", "pyiga", "assemblers.pyx")
    with open(path, 'w') as f:
        f.write(backend.preamble())
        f.write(generate(dim=2))
        f.write(generate(dim=3))

